#!/bin/bash

echo "==========================================="
echo "     MIUI / HyperOS Bloatware Remover"
echo "==========================================="
echo "Starting bloatware removal process..."
echo ""

# List of packages
PACKAGES=(
  com.android.theme.icon.pebble
  com.android.theme.icon.vessel
  com.android.theme.icon.taperedrect
  com.android.theme.icon.teardrop
  com.android.theme.icon.squircle
  com.android.theme.icon.roundedrect
  com.android.theme.icon_pack.circular.android
  com.android.theme.icon_pack.circular.systemui
  com.android.theme.icon_pack.circular.settings
  com.android.theme.icon_pack.filled.android
  com.android.theme.icon_pack.filled.systemui
  com.android.theme.icon_pack.filled.settings
  com.android.theme.icon_pack.rounded.android
  com.android.theme.icon_pack.rounded.systemui
  com.android.theme.icon_pack.rounded.settings
  com.android.theme.icon_pack.kai.android
  com.android.theme.icon_pack.kai.systemui
  com.android.theme.icon_pack.kai.settings
  com.android.theme.icon_pack.sam.android
  com.android.theme.icon_pack.sam.systemui
  com.android.theme.icon_pack.sam.settings
  com.android.theme.icon_pack.victor.android
  com.android.theme.icon_pack.victor.systemui
  com.android.theme.icon_pack.victor.settings
  com.miui.personalassistant
  com.google.android.marvin.talkback
  com.mi.android.globalminusscreen
  com.miui.analytics
  com.miui.cleanmaster
  com.bsp.catchlog
  com.android.providers.downloads.ui
  com.facebook.appmanager
  com.facebook.services
  com.facebook.system
  com.miui.newhome
  com.miui.fm
  com.miui.bugreport
  com.miui.freeform
  com.miui.phrase
  com.xiaomi.glgm
  com.xiaomi.mipicks
  com.google.android.apps.subscriptions.red
  com.miui.hybrid.accessory
  com.xiaomi.joyose
  com.android.email
  com.miui.msa.global
  com.google.android.feedback
  com.miui.micloudsync
  com.xiaomi.payment
  com.android.midrive
  com.miui.mishare.connectivity
  com.xiaomi.mi_connect_service
  com.xiaomi.miplay_client
  com.mi.webkit.core
  com.miui.global.packageinstaller
  com.android.providers.partnerbookmarks
  com.miui.daemon
  com.miui.hybrid
  com.miui.touchassistant
  com.miui.smsextra
  com.miui.translation.kingsoft
  com.miui.translation.xmcloud
  com.miui.miservice
  com.tencent.soter.soterserver
  com.milink.service
  com.miui.vsimcore
  com.miui.wmsvc
  com.miui.weather2
  com.xiaomi.simactivate.service
  com.xiaomi.xmsf
  com.xiaomi.xmsfkeeper
  com.miui.yellowpage
  com.opera.browser.afin
  com.google.android.apps.youtube.music
  com.google.android.videos
  com.tokopedia.tkpd
  com.netflix.ninja
  com.mi.android.globalminusscreen
  com.mi.globalbrowser
  com.xiaomi.calendar
  com.miui.player
  com.miui.videoplayer
  com.miui.gallery
  com.android.theme.icon_pack.circular.themepicker
  com.google.ar.core
  com.google.ar.lens
  com.android.theme.color.black
  com.android.theme.color.green
  com.android.theme.color.ocean
  com.android.theme.color.space
  com.miui.player
  com.miui.compass
  com.google.android.apps.docs
  com.google.android.apps.maps
  com.miui.notes
  com.xiaomi.midrop
  com.google.android.apps.photos
  com.facebook.katana
  com.wdstechnology.android.kryten
  com.xiaomi.scanner
  com.engloryintertech.caping
  com.duokan.phone.remotecontroller
  com.google.android.apps.tachyon
  com.google.android.apps.subscriptions.red
)

for PKG in "${PACKAGES[@]}"; do
  echo ""
  echo "Removing $PKG..."
  adb shell pm uninstall --user 0 "$PKG" >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "✔ $PKG removed successfully."
  else
    echo "✘ Failed to remove $PKG or it was not installed."
  fi
done

echo ""
echo "Bloatware removal process completed."
